services:
  postgresql_db:
    restart: unless-stopped
    image: postgres:17
    container_name: postgres_container
    environment:
      POSTGRES_USER:example_user
      POSTGRES_PASSWORD:example_password
      POSTGRES_DB:example_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data